### ISSUE TITLE
 How about implement `rill.FromSeq` After Golang 1.23 release 

### ISSUE THREAD

**Issue by amikai** [destel/rill#25]
Just an idea. The implementation is similar to `FromChan`. Note that the code haven't test it.

```go
func FromSeq[A any](seq iter.Seq[A], err error) <-chan rill.Try[A] {
	if seq == nil && err == nil {
		return nil
	}

	out := make(chan rill.Try[A])
	go func() {
		defer close(out)

		// error goes first
		if err != nil {
			out <- rill.Try[A]{Error: err}
		}

		for x := range seq {
			out <- rill.Try[A]{Value: x}
		}
	}()

	return out
}

```

**Comment by destel** [comment]
Sure. I am planning to add it when 1.23 goes live. Of course this function will be hidden behind conditional compilation depending on the Go version.
Feel free to create a PR with code, docs and tests if you wish.
